2024-05-05 07:52:01.470 | ERROR    | metagpt.utils.common:log_it:554 - Finished call to 'MCTS.Lingma.ask_llm_location_file.ChatGPT.get_reward' after 135.364(s), this was the 1st time calling it. exp: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
